services:

  mariadb:
    hostname: mariadb
    container_name: mariadb
    build: 
      dockerfile: ./src/mariaDB/Dockerfile
      context: .
      args:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_USER_PASSWORD: ${MYSQL_USER_PASSWORD}
        MYSQL_DATA_BASE: ${MYSQL_DATA_BASE}
    volumes:
      - mariadb-DB:/var/lib/mysql
    networks:
      - w_d_net
    restart: always

  wordpress:
    container_name: wordpress
    build: 
      dockerfile: ./src/wordpress/Dockerfile
      context: .
    env_file:
      - ./.env
    volumes:
      - wordpress-DB:/var/www/html/wordpress
    networks:
      - w_d_net
      - n_w_net
    depends_on:
      - mariadb
    restart: always

  nginx:
    container_name: nginx
    build: 
      dockerfile: ./src/nginx/Dockerfile
      context: .
    ports:
      - "80:80"
    networks:
      - n_w_net
    volumes:
      - wordpress-DB:/var/www/html/wordpress
    restart: always
    depends_on:
      - wordpress
  
volumes:
  mariadb-DB:
    driver: local
    driver_opts:
      type: none
      device: ./data/sql_volume
      o: bind
  wordpress-DB:
    driver: local
    driver_opts:
      type: none
      device: ./data/wordpress_volume
      o: bind

networks:
  n_w_net:
    driver: bridge
  w_d_net:
    driver: bridge


#volumeの定義についてdevice volumeのディレクトリはあらかじめ作っとくのか　今のままだとrootにつくられてしまう