version: '3.9'

services:
  mariadb:
    container_name: mariadb
    build: 
      dockerfile: ./mariadb/dockerfile
      context: .
    volumes:
      mariadb-DB:/var/lib/mysql
  wordpress:
    container_name: wordpress
    build: 
      dockerfile: ./wordpress/dockerfile
      context: .
  nginx:
    container_name: nginx
    build: 
      dockerfile: ./nginx/dockerfile
      context: .

volumes:
  mariadb-DB